### ISSUE TITLE
Bug: contract violation in a module with recursive references

### ISSUE THREAD

**Issue by countvajhula** [lexi-lambda/megaparsack#31] opened 2021-08-26 03:21 UTC
Hi there,
Thank you for making this very useful package. I ran into an error that, while I've been able to scrupulously avoid for the moment, can be reliably reproduced and may be a bug.

I wrote the following parser:
```
(define any-sequence/p
  (or/p (try/p generic-sequence/p)
        (try/p (parametric-sequence/p))))
```

where `generic-sequence/p` and `parametric-sequence/p` are other parsers defined in the same module (and the latter takes an optional argument).

Using this in another parser on certain inputs results in the following error:
```
; chain: contract violation:
; expected: monad?
; given: 'undefined5
; argument position: 2nd
; other arguments...:
;   f: #<procedure:...-lib/data/monad.rkt:31:0>
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   .../private/generic.rkt:475:9 chain
;   .../data/monad.rkt:31:0
;   .../match/compiler.rkt:507:40 f239
;   .../match/compiler.rkt:507:40 f239
;   .../megaparsack/base.rkt:161:3
;   .../megaparsack/base.rkt:300:3
;   .../megaparsack/base.rkt:134:6
;   .../match/compiler.rkt:507:40 f239
;   .../match/compiler.rkt:507:40 f239
;   .../megaparsack/base.rkt:190:0 parse-syntax-box
;   .../megaparsack/base.rkt:200:0 parse-datum
;   .../private/arrow-val-first.rkt:486:18
;   .../private/arrow-val-first.rkt:489:18
;   contract-parser.rkt:3468:0 compile-pass
;   .../private/arrow-higher-order.rkt:375:33 body of "/Users/siddhartha/work/lisp/racket/social-contract/contract/social/c3po/contract-parser.rkt"
```

But replacing instances of `any-sequence/p` with its definition (i.e. the `(or/p ...)` form) in the other parser works correctly.

**Steps to reproduce:**
[This](https://github.com/countvajhula/social-contract/blob/master/contract/social/c3po/contract-parser.rkt#L257-L259) is where the parser is defined (and currently commented out), and right below that, [this](https://github.com/countvajhula/social-contract/blob/c2e69d7c27468e6bfbb71f9f3f435cef5966b443/contract/social/c3po/contract-parser.rkt#L264-L265) is where (among other places) it could be used (but isn't at the moment, due to the error -- e.g. the tests in [`c3po.rkt`](https://github.com/countvajhula/social-contract/blob/c2e69d7c27468e6bfbb71f9f3f435cef5966b443/contract/social/c3po.rkt) fail if it is added).

To reproduce the error:
1. Load the [`contract-parser.rkt`](https://github.com/countvajhula/social-contract/blob/c2e69d7c27468e6bfbb71f9f3f435cef5966b443/contract/social/c3po/contract-parser.rkt) module into a REPL [_Note_: this step works only using Emacs racket-mode's Run command or by using [`enter!`](https://docs.racket-lang.org/reference/interactive.html#%28form._%28%28lib._racket%2Fenter..rkt%29._enter%21%29%29) in a REPL. It does not work either using DrRacket's Run command, or using `require` in a REPL (`contract/p: undefined; cannot reference an identifier before its definition`). This could be related to the issue at hand]
2. Evaluate the forms in [`compiler.rkt`](https://github.com/countvajhula/social-contract/blob/c2e69d7c27468e6bfbb71f9f3f435cef5966b443/contract/social/c3po/compiler.rkt) individually so that `compile-pass` can be used in the REPL
3. Try `(compile-pass "(function/c (listof number?) list?)" map-simple/p)`
4. That should work, and would produce `(map/c number? any/c)` as output
5. Now, uncomment those lines defining the `any-sequence/p` parser, and use it in the `map-simple/p` parser below it (just replacing one instance is sufficient), and save the file.
6. Re-run steps 1-3 (if in a REPL, you may need to exit it and restart a new one).
7. This should now show the above error

Note that the code in the `any-sequence/p` parser is identical to the code used in `map-simple/p`, but replacing it with the `any-sequence/p` identifier instead of its definition results in the error happening.

**Observations:**
I noticed that manually evaluating `any-sequence/p` after step 2 allows it to work correctly. This seems to suggest that it has something to do with the `any-sequence/p` identifier not being resolved correctly a priori. So maybe this is more of Racket module loading issue with recursive references being present (e.g. `contract/p` -> `map/p` -> ... `contract/p`)? In this case, since we are likely to have recursive references in parsers, is there a recommended way to avoid issues like this one?

**Comment by lexi-lambda** [comment] 2022-01-07 21:50
The fact that it only works in the REPL is, indeed, the source of the problem. Your program is analogous to this one:

```racket
(define x (+ 1 y))
(define y 2)
```

However, it’s worth saying that on Racket HEAD, I still get the more immediate error:

```
Welcome to Racket v8.3.0.11 [cs].
> (enter! "contract-parser.rkt")
; contract/p: undefined;
;  cannot reference an identifier before its definition
```

Perhaps you have something configured differently, or perhaps the behavior changed since this issue was opened, I’m not sure.

Regardless, the problem is fundamentally that you are evaluating a reference to `contract/p` before it has been initialized. This is tricky, because `contract/p` is, after all, recursive, and it needs to be able to reference itself. Fortunately, self-recursive *references* are fine as long as evaluating the definition’s right-hand-side does not require *evaluating* the reference. This is why recursive functions are allowed: the self-reference is only evaluated when the function is *called*.

Essentially, this means your self-reference to `contract/p` has to be delayed somehow, probably by moving it under a lambda. For example, compare these two parser definitions:

```racket
;; okay
(define foo/p (do (char/p #\a)
                  foo/p))
;; NOT okay
(define bar/p (or/p (char/p #\a)
                    bar/p))
```

Why is `foo/p` okay? Because `do` expands to a use of `chain`, so the definition of `foo/p` is equivalent to this:

```racket
(define foo/p (chain (λ (_x) foo/p)
                     (char/p #\a)))
```

Crucially, the self-reference appears here under a lambda (and `chain` returns without applying that lambda), so the evaluation of `foo/p` is delayed, and there is no problem. This knowledge allows us to fix our definition of `bar/p` with a little trick:

```racket
(define bar/p (or/p (char/p #\a)
                    (do void/p
                        bar/p)))
```

This arranges for the reference to `bar/p` to appear under a lambda, so it’s no longer evaluated too early. And since `void/p` doesn’t do anything, it’s equivalent to the original program.

However, this is sort of awkward. For that reason, I’ve just pushed 7b58112152e9a06a63f7084c76b794fdf0df3d2f, which adds a new `delay/p` form to `megaparsack`. This is essentially just convenient syntactic sugar for the above trick, but it is a little more efficient:

```racket
;; okay
(define bar/p (or/p (char/p #\a)
                    (delay/p bar/p)))
```

You should be able to use `delay/p` to solve your problem, so I’m going to call this issue closed.

**Closed as completed by lexi-lambda** 2022-01-07 21:50 UTC

**Comment by countvajhula** [comment] 2022-01-08 20:14
All that makes sense. Thanks for the explanation and the new form - works like a charm!

> Perhaps you have something configured differently, or perhaps the behavior changed since this issue was opened, I’m not sure.

FTR, that's what I'm getting now, too, so I'm not sure either 🤷
